providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = '22'

# https://hub.nuxt.com/docs/database/migrations#generating-migrations
[start]
cmd = "pnpm exec nuxt db migrate && node .output/server/index.mjs"
